# Source directory for Eleventy
source: src

paths:
  uploads: uploads
  static: ''
  data: _data
  layouts: _layouts
  includes: _includes

collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
    _enabled_editors:
      - visual
      - content
      - data
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  original_site:
    path: original-site
    icon: diagonal_line
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - data
  - visual
  - content
_inputs:
  $.description:
    type: textarea
    cascade: true
  $.title:
    type: text
    cascade: true
_editables:
  text:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    copyformatting: true
    italic: true
    link: true
    redo: true
    removeformat: true
    strike: true
    subscript: true
    superscript: true
    underline: true
    undo: true
  block:
    allow_custom_markup: true
    remove_custom_markup: false
    bold: true
    italic: true
    link: true
    redo: true
    undo: true
    removeformat: true
    bulletedlist: true
    numberedlist: true
editor:
  default_path: /
source_editor:
  tab_size: 2
  theme: atomone
  show_gutter: true
timezone: America/Denver
markdown:
  engine: commonmark
  options:
    html: true
