source: /
paths:
  uploads: uploads
  static: ''
_enabled_editors:
  - data
  - visual
  - content
commit_templates:
  - label:
    template_string:
    template_path:
    _inputs:
    extra_data:
editor:
  default_path:
source_editor:
  tab_size: 2
  theme: vscode_dark
  show_gutter: true
timezone: America/Denver
markdown:
  engine: commonmark
  options:
    html: true
